/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThumbNail.java
 *
 * Created on 11.04.2010, 16:42:35
 */

package celsius.components.tableTabs;

import celsius.data.TableRow;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author cnsaeman
 */
public class Thumbnail extends javax.swing.JPanel {

    public int spx;
    public int spy;

    public TableRow tableRow;
    public final CelsiusTable celsiusTable;

    /** Creates new form ThumbNail */
    public Thumbnail(TableRow tr, CelsiusTable ct) {
        celsiusTable=ct;
        initComponents();
        spx=ct.MF.RSC.guiTools.guiScale(140);
        spy=ct.MF.RSC.guiTools.guiScale(160);
        setPreferredSize(new Dimension(spx-3,spy-3));
        setMaximumSize(new Dimension(spx-3,spy-3));
        jLIcon.setPreferredSize(new Dimension(spx-3,spy-20-3));
        jLIcon.setMaximumSize(new Dimension(spx-3,spy-20-3));
        setBackground(Color.white);
        jLIcon.setAlignmentX(JLabel.CENTER_ALIGNMENT);
        jLIcon.setAlignmentY(JLabel.CENTER_ALIGNMENT);
        jLIcon.setHorizontalAlignment(JLabel.CENTER);
        jLIcon.addMouseListener(celsiusTable);
        jTFDesc.addMouseListener(celsiusTable);
        tableRow=tr;
        jLIcon.setName(tableRow.id);
        jTFDesc.setName(tableRow.id);
        jTFDesc.setText("loading");
        celsiusTable.TPE.execute(new ThreadLoadThumbnail(this,celsiusTable.MF.RSC));
    }

    public void updateTableRow() {
        celsiusTable.TPE.execute(new ThreadLoadThumbnail(this,celsiusTable.MF.RSC));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLIcon = new javax.swing.JLabel();
        jTFDesc = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());
        add(jLIcon, java.awt.BorderLayout.CENTER);

        jTFDesc.setFont(jTFDesc.getFont().deriveFont(jTFDesc.getFont().getStyle() & ~java.awt.Font.BOLD, jTFDesc.getFont().getSize()-2));
        jTFDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jTFDesc, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLIcon;
    public javax.swing.JLabel jTFDesc;
    // End of variables declaration//GEN-END:variables

    public void setWhite() {
        setComponentPopupMenu(null);
        setBackground(Color.WHITE);
        repaint();
    }

    public void setGrey() {
        setComponentPopupMenu(celsiusTable.MF.jPMItemTable);
        setBackground(UIManager.getColor("Table[Enabled+Selected].textBackground"));
        repaint();
    }

}
