/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThumbNailView.java
 *
 * Created on 03.04.2010, 14:08:44
 */

package celsius.components.tableTabs;

import celsius.data.TableRow;
import celsius.gui.WrapLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author cnsaeman
 */
public class ThumbnailView extends javax.swing.JPanel implements TableModelListener, KeyListener {

    public int spx;
    public int spy;

    CelsiusTable celsiusTable;

    boolean updating;

    public int w;
    public int h;
    public int tx;
    public int ty;

    private final ArrayList<Thumbnail> thumbnails;

    /** Creates new form ThumbNailView */
    public ThumbnailView(CelsiusTable ct) {
        initComponents();
        setLayout(new WrapLayout(FlowLayout.LEFT));
        thumbnails=new ArrayList<>();
        celsiusTable=ct;
        addKeyListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void updateView() {
        updating=true; // #### is beeing called four times when changing categories?
        removeAll();
        thumbnails.clear();
        for (TableRow tableRow : celsiusTable.celsiusTableModel.tableRows) {
            if (thumbnails.size()<100) { // #### Temp restriction until threadexecutorpool really working
                Thumbnail TN=new Thumbnail(tableRow,celsiusTable);
                thumbnails.add(TN);
                add(TN);
            }
        }
        updating=false;
    }

    public void addItem(int i) {
        Thumbnail TN=new Thumbnail(celsiusTable.getRow(i),celsiusTable);
        thumbnails.add(i,TN);
        System.out.println("Adding "+celsiusTable.getRow(i));
        add(TN,i);
    }

    @Override
    public void remove(int i) {
        if (thumbnails.size()>i) thumbnails.remove(i);
        if (this.getComponentCount()>i) super.remove(i);
    }

    public void tableChanged(TableModelEvent e) {
        if (updating) return;
        if (!Thread.currentThread().getName().startsWith("AWT-Event")) return;
        updateView();
        if (!celsiusTable.celsiusTableModel.tableview) {
            if (e.getType()==TableModelEvent.DELETE) {
                for (int i=e.getLastRow();i>=e.getFirstRow();i--) {
                    remove(i);
                }
            }
            if (e.getType()==TableModelEvent.INSERT) {
                System.out.println("INSERT NOT CAPUTRED");
            }
            if (e.getType()==TableModelEvent.UPDATE) {
                if (e.getLastRow()==-1) {
                    updateView();
                } else {
                    for (int i=e.getFirstRow();i<e.getLastRow()+1;i++) {
                        thumbnails.get(i).updateTableRow();
                    }
                }
            }
        }
    }

    public void modifySelection(int i,boolean extend) {
        boolean mod=false;
        if ((i==0) && (celsiusTable.selectedlast!=0)) {
            celsiusTable.selectedlast=0; mod=true;
        }
        if ((i==1000) && (celsiusTable.selectedlast!=celsiusTable.celsiusTableModel.tableRows.size()-1)) {
            celsiusTable.selectedlast=celsiusTable.celsiusTableModel.tableRows.size()-1; mod=true;
        }
        if ((i>0) && (i<999) && (celsiusTable.selectedlast<celsiusTable.celsiusTableModel.tableRows.size() - i+1)) {
            celsiusTable.selectedlast+=i; mod=true;
        }
        if ((i<0) && (celsiusTable.selectedlast>i-1)) {
            celsiusTable.selectedlast+=i; mod=true;
        }
        if (mod) {
            if (!extend) celsiusTable.selectedfirst = celsiusTable.selectedlast;
            if (celsiusTable.selectedlast > celsiusTable.selectedfirst) {
                celsiusTable.jtable.getSelectionModel().setSelectionInterval(celsiusTable.selectedfirst, celsiusTable.selectedlast);
            } else {
                celsiusTable.jtable.getSelectionModel().setSelectionInterval(celsiusTable.selectedlast, celsiusTable.selectedfirst);
            }
            adjustSelection();
        }
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
    }

    @Override
    public void keyReleased(KeyEvent e) {
        // TODO: needs to be optimized for lines that are partially filled
        int tx=(!thumbnails.isEmpty() ? getWidth()/(thumbnails.get(0).getWidth()) : 0);
        if (e.getKeyCode() == 36)
            modifySelection(0, e.isShiftDown());
        if (e.getKeyCode() == 37)
            modifySelection(-1,e.isShiftDown());
        if (e.getKeyCode() == 39)
            modifySelection(1,e.isShiftDown());
        if (e.getKeyCode() == 38)
            modifySelection(-tx,e.isShiftDown());
        if (e.getKeyCode() == 40)
            modifySelection(tx,e.isShiftDown());
        if (e.getKeyCode()==35) 
            modifySelection(1000,e.isShiftDown());
    }
    
    public void adjustSelection() {
        boolean mode=false;
        int b=celsiusTable.selectedfirst;
        int e=celsiusTable.selectedlast;
        if (b>e) {
            b=celsiusTable.selectedlast;
            e=celsiusTable.selectedfirst;
        }
        for (int i=0;i<thumbnails.size();i++) {
            if (i==b) mode=!mode;
            if (mode) thumbnails.get(i).setGrey();
            else thumbnails.get(i).setWhite();
            if (i==e) mode=!mode;
        }
        scrollRectToVisible(thumbnails.get(celsiusTable.selectedlast).getBounds());
    }

    public void update(TableRow row) {
        int i=celsiusTable.celsiusTableModel.IDs.indexOf(row.id);
        thumbnails.get(i).updateTableRow();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public void clear() {
        removeAll();
    }

}
