/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChooseSearchResult.java
 *
 * Created on 19.02.2010, 23:22:02
 */

package celsius.gui;

import celsius.Resources;
import atlantis.tools.Parser;
import javax.swing.DefaultListModel;

/**
 *
 * @author cnsaeman
 */
public class ChooseSearchResult extends javax.swing.JDialog {

    public int result;
    private final Resources RSC;

    /** Creates new form ChooseSearchResult */
    public ChooseSearchResult(celsius.gui.MainFrame parent, String results,Resources rsc) {
        super(parent, true);
        RSC=rsc;
        initComponents();
        DefaultListModel DLM=new DefaultListModel();
        String[] res=results.split("\\|");
        String tmp;
        for (int i=0;i<res.length;i++) {
            tmp=res[i];
            tmp=Parser.decodeHTML(tmp);
            DLM.addElement(tmp);
        }
        jLSearchResults.setModel(DLM);
        result=-1;
        GUIToolBox.centerDialog(this,parent);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnOK = new javax.swing.JButton();
        jBtnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLSearchResults = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose search result");

        jBtnOK.setText("OK");
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOKActionPerformed(evt);
            }
        });

        jBtnCancel.setText("Cancel");
        jBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelActionPerformed(evt);
            }
        });

        jLSearchResults.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jLSearchResults.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLSearchResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSearchResultsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLSearchResults);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnOK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnOK)
                    .addComponent(jBtnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBtnCancelActionPerformed

    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOKActionPerformed
        result=jLSearchResults.getSelectedIndex();
        this.setVisible(false);
    }//GEN-LAST:event_jBtnOKActionPerformed

    private void jLSearchResultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSearchResultsMouseClicked
        if (evt.getClickCount() == 2) {
            result=jLSearchResults.getSelectedIndex();
            this.setVisible(false);
        }
    }//GEN-LAST:event_jLSearchResultsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancel;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JList jLSearchResults;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}


