package celsius.gui;

import celsius.Resources;
import java.awt.event.KeyListener;
import javax.swing.text.Document;

/**
 *
 * @author cnsaeman
 */
public class ClearEdit extends javax.swing.JPanel {

    Resources RSC;
    
    /**
     * Creates new form jClearEdit
     */
    public ClearEdit(Resources RSC, String defaultText) {
        this.RSC=RSC;
        initComponents();
        jETFContent.setDefaultText(defaultText);
    }
    
    public String getText() {
        return(jETFContent.getText());
    }
    
    @Override
    public void requestFocus() {
        jETFContent.requestFocus();
    }
    
    public void addKeyTypedListener(KeyListener kl) {
        jETFContent.addKeyListener(kl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnClear = new javax.swing.JButton();
        jETFContent = new celsius.gui.jExtTextField();

        jBtnClear.setIcon(RSC.icons.getScaledIcon("closebtn"));
        jBtnClear.setMaximumSize(new java.awt.Dimension(60, 60));
        jBtnClear.setMinimumSize(new java.awt.Dimension(6, 6));
        jBtnClear.setPreferredSize(new java.awt.Dimension(RSC.guiScale(25), RSC.guiScale(25)));
        jBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jETFContent, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jETFContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClearActionPerformed
        jETFContent.resetText();
    }//GEN-LAST:event_jBtnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClear;
    private celsius.gui.jExtTextField jETFContent;
    // End of variables declaration//GEN-END:variables

    public Document getDocument() {
        return(jETFContent.getDocument());
    }
    
    public jExtTextField getTF() {
        return(jETFContent);
    }

    public void selectAll() {
        jETFContent.selectAll();
    }
}
