/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DialogEditLibrary.java
 *
 * Created on 18.02.2010, 22:23:30
 */

package celsius.gui;

import celsius.data.KeyValueTableModel;
import celsius.data.Library;
import celsius.Resources;
import celsius.tools.Parser;
import celsius.tools.TextFile;
import celsius.tools.ToolBox;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author cnsaeman
 */
public class EditLibrary extends javax.swing.JDialog {

    private final Library library;
    private final MainFrame MF;
    private final Resources RSC;
    private final KeyValueTableModel KVTM;

    /** Creates new form DialogEditLibrary */
    public EditLibrary(MainFrame mf, Library lib) {
        super(mf, true);
        MF=mf;
        RSC=MF.RSC;
        library=lib;
        initComponents();
        jTPEditMode.setTabComponentAt(0,new TabLabel("General settings",Resources.editTabIcon2,RSC,null,false));
        jTPEditMode.setTabComponentAt(1,new TabLabel("Templates",Resources.templateTabIcon,RSC,null,false));
        jTPEditMode.setTabComponentAt(2,new TabLabel("CSS style sheet",Resources.styleSheetTabIcon,RSC,null,false));
        KVTM=new KeyValueTableModel("Property","Value");
        for (String t : RSC.LibraryFields) {
            KVTM.addRow(Parser.lowerEndOfWords(t), library.config.get(t));
        }
        jTMain.setModel(KVTM);
        jTMain.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTMain.getColumnModel().getColumn(0).setMaxWidth(150);

        jTAStyleSheet.setText(library.config.get("css-style"));
        jTAStyleSheet.setFont(RSC.stdFontMono());
        jTAStyleSheet.setCaretPosition(0);
        
        jTATemplate.setText(library.getHTMLTemplate(0).templateString);
        jTATemplate.setFont(RSC.stdFontMono());
        jTAStyleSheet.setCaretPosition(0);

        GUIToolBox.centerDialog(this,mf);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTPEditMode = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTMain = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTATemplate = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jCBHTMLtemplate = new javax.swing.JComboBox();
        jBtnApply2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTAStyleSheet = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jBtnApply3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBtnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Library Properties");

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jTMain.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMainMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTMain);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        jScrollPane1.getAccessibleContext().setAccessibleDescription("");

        jTPEditMode.addTab("tab1", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jTATemplate.setColumns(20);
        jTATemplate.setRows(5);
        jScrollPane3.setViewportView(jTATemplate);

        jPanel4.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jCBHTMLtemplate.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Document", "Person", "Category", "Multiple Documents", "Identifier search", "General search", "Keyword search", "Links tab", "Just added" }));
        jCBHTMLtemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBHTMLtemplateActionPerformed(evt);
            }
        });
        jPanel7.add(jCBHTMLtemplate);

        jBtnApply2.setText("Apply");
        jBtnApply2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApply2ActionPerformed(evt);
            }
        });
        jPanel7.add(jBtnApply2);

        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        jTPEditMode.addTab("tab2", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jTAStyleSheet.setColumns(20);
        jTAStyleSheet.setRows(5);
        jScrollPane2.setViewportView(jTAStyleSheet);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jBtnApply3.setText("Apply");
        jBtnApply3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApply3ActionPerformed(evt);
            }
        });
        jPanel6.add(jBtnApply3);

        jPanel5.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jTPEditMode.addTab("tab3", jPanel5);

        jPanel1.add(jTPEditMode, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jBtnDone.setText("Done");
        jBtnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDoneActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnDone);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDoneActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBtnDoneActionPerformed

    private void jBtnApply2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApply2ActionPerformed
        int iM=jCBHTMLtemplate.getSelectedIndex();
        library.setHTMLTemplate(iM, jTATemplate.getText());
}//GEN-LAST:event_jBtnApply2ActionPerformed

    private void jBtnApply3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApply3ActionPerformed
        library.putConfig("css-style", jTAStyleSheet.getText());
        library.setStyleSheet();
        RSC.MF.guiInfoPanel.updateCSS();
    }//GEN-LAST:event_jBtnApply3ActionPerformed

    private void jCBHTMLtemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBHTMLtemplateActionPerformed
        int iM=jCBHTMLtemplate.getSelectedIndex();
        jTATemplate.setText(library.getHTMLTemplate(iM).templateString);
        jTATemplate.setCaretPosition(0);
    }//GEN-LAST:event_jCBHTMLtemplateActionPerformed

    private void jTMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMainMouseClicked
        if (evt.getClickCount() == 2 && evt.getButton() == MouseEvent.BUTTON1) {
            editCurrentlySelectedKey();
        }
    }//GEN-LAST:event_jTMainMouseClicked

    public void editCurrentlySelectedKey() {
        String key = ((String) jTMain.getModel().getValueAt(jTMain.getSelectedRow(), 0));
        // standard text editor
        String value = library.config.get(key.toLowerCase());
        MultiLineEditor MLE = new MultiLineEditor(RSC, "Edit value", value);
        MLE.setVisible(true);
        if (!MLE.cancel) {
            value = MLE.text;
            if (value.equals("<unknown>")) {
                value = null;
            }
            library.putConfig(key.toLowerCase(), value);
            KVTM.put(key,value);
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApply2;
    private javax.swing.JButton jBtnApply3;
    private javax.swing.JButton jBtnDone;
    private javax.swing.JComboBox jCBHTMLtemplate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTAStyleSheet;
    private javax.swing.JTextArea jTATemplate;
    private javax.swing.JTable jTMain;
    private javax.swing.JTabbedPane jTPEditMode;
    // End of variables declaration//GEN-END:variables

}
