/*
 * EditLibraryPlugins.java
 *
 * Created on 18.02.2010, 22:23:30
 */

package celsius.gui;

import celsius.data.Library;
import celsius.tools.Plugins;
import celsius.Resources;
import celsius.tools.Parser;
import celsius.tools.ToolBox;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author cnsaeman
 */
public final class EditLibraryPlugins extends javax.swing.JDialog {

    private final Library library;
    private final MainFrame MF;
    private final Plugins plugins;

    private final HashMap<String,EditLibraryPluginPanel> panels;

    /** Creates new form EditLibraryPlugins */
    public EditLibraryPlugins(MainFrame mf, Library lib) {
        super(mf, true);
        MF=mf;
        plugins=MF.RSC.plugins;
        library=lib;
        initComponents();
        setTitle("Manage plugins in active library " + library.name);
        panels=new HashMap<>();
        for(String type : Plugins.types) {
            EditLibraryPluginPanel ELPP=new EditLibraryPluginPanel(MF.RSC,this,type,plugins);
            panels.put(type,ELPP);
            jPanel3.add(ELPP);
        }
        jLPlugins.setModel(plugins.getPluginsDLM());
        this.pack();
        this.setSize(MF.RSC.guiScale(800), MF.RSC.guiScale(700));
        GUIToolBox.centerDialog(this,mf);
    }

    public String getCurrentlySelectedPlugin() {
        return((String)jLPlugins.getSelectedValue());
    }

    public void saveModels() {
        for (String type : Plugins.types) {
            library.putConfig("plugins-"+type, panels.get(type).getStringList());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLPlugins = new javax.swing.JList();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTAPlugin = new javax.swing.JEditorPane();
        jPanel6 = new javax.swing.JPanel();
        jBtnReload = new javax.swing.JButton();
        jBtnSave = new javax.swing.JButton();
        jBtnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Available Plugins:");

        jLPlugins.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLPluginsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jLPlugins);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(3, 2, 5, 5));
        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        jLabel6.setText("Selected Plugin:");

        jScrollPane5.setViewportView(jTAPlugin);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jBtnReload.setText("Reload all Plugins");
        jBtnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReloadActionPerformed(evt);
            }
        });
        jPanel6.add(jBtnReload);

        jBtnSave.setText("Save Changes");
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });
        jPanel6.add(jBtnSave);

        jBtnDone.setText("Done");
        jBtnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDoneActionPerformed(evt);
            }
        });
        jPanel6.add(jBtnDone);

        jPanel2.add(jPanel6, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDoneActionPerformed
        this.setVisible(false);
        plugins.updatePlugins();
        this.dispose();
}//GEN-LAST:event_jBtnDoneActionPerformed

    private void jLPluginsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLPluginsValueChanged
        String name=(String)jLPlugins.getSelectedValue();
        jTAPlugin.setContentType("text/html");
        jTAPlugin.setText(plugins.getText(name));
        jTAPlugin.setCaretPosition(0);
        String ptype=plugins.get(name).metaData.get("type");
        for (String type : Plugins.types) {
            panels.get(type).jBtnAdd.setEnabled(Parser.listContains(ptype, type)); 
        }
        if (Parser.listContains(ptype, "interactive")) panels.get("manual-items").jBtnAdd.setEnabled(true);
    }//GEN-LAST:event_jLPluginsValueChanged

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        saveModels();
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReloadActionPerformed
        MF.reloadPlugins();
    }//GEN-LAST:event_jBtnReloadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDone;
    private javax.swing.JButton jBtnReload;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JList jLPlugins;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JEditorPane jTAPlugin;
    // End of variables declaration//GEN-END:variables

}
