/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package celsius.gui;

import celsius.Resources;
import celsius.tools.Plugins;
import celsius.tools.ToolBox;
import java.awt.Dimension;
import javax.swing.DefaultListModel;

/**
 *
 * @author cnsaeman
 */
public class EditLibraryPluginPanel extends javax.swing.JPanel {
    
    public final Resources RSC;
    public DefaultListModel DLM;
    public final String type;
    public final EditLibraryPlugins ELP;

    /**
     * Creates new form EditLibraryPluginPanel
     */
    public EditLibraryPluginPanel(Resources rsc,EditLibraryPlugins elp, String t, Plugins plugins) {
        RSC=rsc;
        ELP=elp;
        type=t;
        initComponents();
        jLTitle.setText(type);
        jBtnAdd.setEnabled(false);
        jBtnUp.setEnabled(false);
        jBtnDown.setEnabled(false);
        jBtnRemove.setEnabled(false);
        DLM=new DefaultListModel();
        String libraryPlugins=RSC.getCurrentlySelectedLibrary().config.get("plugins-"+type);
        if (libraryPlugins!=null) {
            for (String pluginL1 : ToolBox.stringToArray(libraryPlugins)) {
                DLM.addElement(pluginL1);
            }
        }
        jList.setModel(DLM);
        this.setPreferredSize(new Dimension(RSC.guiScale(261),RSC.guiScale(142)));
    }

    public String getStringList() {
        String stringList=new String("");
        for (int i=0;i<DLM.getSize();i++) 
            stringList+="|"+(String)DLM.getElementAt(i);
        if (stringList.length()>0) stringList=stringList.substring(1);
        return(stringList);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jBtnAdd = new javax.swing.JButton();
        jBtnUp = new javax.swing.JButton();
        jBtnDown = new javax.swing.JButton();
        jBtnRemove = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLTitle.setText("jLabel1");
        jPanel1.add(jLTitle);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(RSC.stdBorder());

        jBtnAdd.setText("Add");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnUp.setText("Move up");
        jBtnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpActionPerformed(evt);
            }
        });

        jBtnDown.setText("Move down");
        jBtnDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDownActionPerformed(evt);
            }
        });

        jBtnRemove.setText("Remove");
        jBtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDown)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnRemove)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, java.awt.BorderLayout.EAST);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        String entry=ELP.getCurrentlySelectedPlugin();
        DLM.addElement(entry);
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jBtnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpActionPerformed
        int pos=jList.getSelectedIndex();
        String entry=jList.getSelectedValue();
        DLM.remove(pos);
        DLM.add(pos-1,entry);
        jList.setSelectedIndex(pos-1);
    }//GEN-LAST:event_jBtnUpActionPerformed

    private void jBtnDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDownActionPerformed
        int pos=jList.getSelectedIndex();
        String entry=jList.getSelectedValue();
        DLM.remove(pos);
        DLM.add(pos+1,entry);
        jList.setSelectedIndex(pos+1);
    }//GEN-LAST:event_jBtnDownActionPerformed

    private void jBtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoveActionPerformed
        DLM.remove(jList.getSelectedIndex());
    }//GEN-LAST:event_jBtnRemoveActionPerformed

    private void jListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListValueChanged
        int pos=jList.getSelectedIndex();
        jBtnUp.setEnabled(pos > 1);
        jBtnDown.setEnabled((pos>-1) && (pos<DLM.getSize()-1));
        jBtnRemove.setEnabled(pos>-1);
    }//GEN-LAST:event_jListValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnDown;
    private javax.swing.JButton jBtnRemove;
    private javax.swing.JButton jBtnUp;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
