package celsius.gui;

import celsius.Resources;
import celsius.gui.MultiLineEditor;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TabLabel.java
 *
 * Created on 28.03.2010, 19:26:37
 */

/**
 *
 * @author cnsaeman
 */
public class MLInfoEditor extends javax.swing.JPanel {

    public final Resources RSC;
    public final String title;
    public String value;

    /** Creates new form TabLabel */
    public MLInfoEditor(Resources r, String t, String v) {
        RSC=r;
        title=t;
        value=v;
        initComponents();
        jTF.setText(v);
        jTF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnEdit = new javax.swing.JButton();
        jTF = new javax.swing.JTextField();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jBtnEdit.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jBtnEdit.setText("...");
        jBtnEdit.setPreferredSize(new java.awt.Dimension(23, 23));
        jBtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditActionPerformed(evt);
            }
        });
        add(jBtnEdit, java.awt.BorderLayout.EAST);
        add(jTF, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditActionPerformed
        MultiLineEditor DMLE = new MultiLineEditor(RSC, "Edit "+title, value);
        DMLE.setVisible(true);
        if (!DMLE.cancel) {
            value=DMLE.text;
            jTF.setText(value);
        }
    }//GEN-LAST:event_jBtnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEdit;
    private javax.swing.JTextField jTF;
    // End of variables declaration//GEN-END:variables

}
