//
// Celsius Library System v2
// (w) by C. Saemann
//
// DialogMultiLineEditor.java
//
// This class contains a multiline editor dialog frame
//
// typesafe, completed
// 
// checked 15.09.2007
//

package celsius.gui;

import celsius.Resources;
import celsius.tools.ToolBox;

/**
 *
 * @author  cnsaeman
 */
public class MultiLineMessage extends javax.swing.JDialog {
    
    public String text;
    private Resources RSC;
    
    /** Creates new form DialogMultiLineEditor */
    public MultiLineMessage(Resources rsc, String title, String txt) {
        super(rsc.MF, true);
        RSC=rsc;
        setIconImage(RSC.celsiusIcon);
        this.setTitle(title);
        initComponents();
        text=txt;
        jText.setText(text);
        jText.setWrapStyleWord(true);
        jText.setCaretPosition(0);
        this.setSize(RSC.guiScale(400), RSC.guiScale(300));
        GUIToolBox.centerDialog(this,rsc.MF);
    }

    public void setLineWrapping(boolean b) {
        jText.setLineWrap(b);
        if (b) jText.setWrapStyleWord(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jText = new javax.swing.JTextArea();
        jBtnApply = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jText.setColumns(20);
        jText.setLineWrap(true);
        jText.setRows(5);
        jText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jText);

        jBtnApply.setText("OK");
        jBtnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnApply, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnApply)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApplyActionPerformed
        text=jText.getText();
        setVisible(false);
    }//GEN-LAST:event_jBtnApplyActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApply;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jText;
    // End of variables declaration//GEN-END:variables
    
}
