package celsius.gui;

import celsius.gui.CelsiusTable;
import celsius.Resources;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TabLabel.java
 *
 * Created on 28.03.2010, 19:26:37
 */

/**
 *
 * @author cnsaeman
 */
public class TabLabel extends javax.swing.JPanel implements ActionListener {

    public final String II;
    public final String title;
    public final Resources RSC;
    public final CelsiusTable DT;

    /** Creates new form TabLabel */
    public TabLabel(String t, String i, Resources rsc, CelsiusTable dt, boolean btn) {
        RSC=rsc;
        initComponents();
        II=i;
        title=t;
        DT=dt;
        //jLbl.setFont(new java.awt.Font("Arial", 0, RSC.guiScale(12)));
        jLbl.setText(t);
        jLbl.setIcon(RSC.getScaledIcon(II));
        jLbl.setIconTextGap(RSC.guiScale(5));
        if (btn) {
            JButton BtnSwitch=new JButton();
            BtnSwitch.setIcon(RSC.getScaledIcon("iconmonstr-picture-1.svg.24"));
            BtnSwitch.setPreferredSize(new Dimension(RSC.guiScale(16),RSC.guiScale(15)));
            BtnSwitch.setBorderPainted(false);
            BtnSwitch.setOpaque(false);
            BtnSwitch.setContentAreaFilled(false);
            BtnSwitch.addActionListener(this);
            BtnSwitch.setName("switch");
            JButton BtnClose=new JButton();
            BtnClose.setIcon(RSC.getScaledIcon("closebtn_sm"));
            BtnClose.setPreferredSize(new Dimension(RSC.guiScale(16),RSC.guiScale(15)));
            BtnClose.setBorderPainted(false);
            BtnClose.setOpaque(false);
            BtnClose.setContentAreaFilled(false);
            BtnClose.addActionListener(this);
            BtnClose.setName("close");
            JPanel panel=new JPanel();
            panel.add(BtnSwitch);
            panel.add(BtnClose);
            panel.setOpaque(false);
            this.add(panel,BorderLayout.EAST);
            
        } else {
            if (t.equals(""))
                jLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
            else
                jLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(RSC.guiScale(2), RSC.guiScale(3), 0, RSC.guiScale(3)));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 2, 4, 2));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        jLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 10));
        jLbl.setMaximumSize(new java.awt.Dimension(100000, 15));
        add(jLbl, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLbl;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        if (((JButton)e.getSource()).getName().equals("switch")) {
            DT.switchView();
        }
        if (((JButton)e.getSource()).getName().equals("close")) {
            DT.close();
        }
    }

}
