/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewerText.java
 *
 * Created on 29.12.2009, 22:06:45
 */

package celsius.gui;

import celsius.Resources;
import celsius.gui.MainFrame;
import celsius.gui.SingleLineEditor;
import celsius.tools.FFilter;
import celsius.tools.InteractiveFileCopy;
import atlantis.tools.TextFile;
import celsius.tools.ToolBox;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author cnsaeman
 */
public class ViewerText extends javax.swing.JFrame {

    Resources RSC;
    String filename;
    String label;
    String search;
    int pos;

    /** Creates new form ViewerText */
    public ViewerText(Resources rsc,String fn,String lb) {
        initComponents();
        RSC=rsc;
        filename=fn;
        label=lb;
        jStatus.setText(lb);
        jTAContent.setText(TextFile.ReadOutFile(fn));
        jTAContent.setCaretPosition(0);
        final Image image = Toolkit.getDefaultToolkit().getImage(MainFrame.class.getResource("images/celsius.gif"));
        setIconImage(image);
        pos=0;
        search="";
        this.setSize(800, 400);
        GUIToolBox.centerFrame(this);
    }

    private void findNext() {
        if (search.length()==0) return;
        int p=jTAContent.getText().indexOf(search,pos);
        if ((pos==0) && (p==-1)) {
            RSC.showWarning("Text not found.", "No result");
            return;
        }
        if (p==-1) {
            if (RSC.askQuestionYN("Text not found in remainder of the document.\nStart search from the top?", "Please confirm:")==JOptionPane.YES_OPTION) {
                pos=0;
                findNext();
            }
            return;
        }
        pos=p;
        jTAContent.requestFocus();
        jTAContent.setCaretPosition(pos);
        jTAContent.select(pos,pos+search.length());
        pos++;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAContent = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jStatus = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMISaveCopy = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMIClose = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMIFind = new javax.swing.JMenuItem();
        jMIFindNext = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Text Viewer");

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));

        jTAContent.setColumns(20);
        jTAContent.setEditable(false);
        jTAContent.setLineWrap(true);
        jTAContent.setRows(5);
        jTAContent.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTAContent);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 815, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 813, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jMenu1.setText("File");

        jMISaveCopy.setText("Save Copy");
        jMISaveCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMISaveCopyActionPerformed(evt);
            }
        });
        jMenu1.add(jMISaveCopy);
        jMenu1.add(jSeparator1);

        jMIClose.setText("Close");
        jMIClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMICloseActionPerformed(evt);
            }
        });
        jMenu1.add(jMIClose);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMIFind.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMIFind.setText("Find");
        jMIFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFindActionPerformed(evt);
            }
        });
        jMenu2.add(jMIFind);

        jMIFindNext.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMIFindNext.setText("Find next");
        jMIFindNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIFindNextActionPerformed(evt);
            }
        });
        jMenu2.add(jMIFindNext);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMICloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMICloseActionPerformed
       setVisible(false);
       dispose();
    }//GEN-LAST:event_jMICloseActionPerformed

    private void jMISaveCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMISaveCopyActionPerformed
        JFileChooser FC = new JFileChooser();
        FC.setDialogTitle("Indicate the target file");
        FC.setDialogType(JFileChooser.SAVE_DIALOG);
        FC.setFileFilter(new FFilter("_ALL", "All files"));
        RSC.adjustComponents(FC.getComponents());
        // abgebrochen?
        if (FC.showSaveDialog(this) != JFileChooser.CANCEL_OPTION) {
           (new InteractiveFileCopy(RSC.MF,filename, FC.getSelectedFile().getAbsolutePath(),RSC)).go();
        }
    }//GEN-LAST:event_jMISaveCopyActionPerformed

    private void jMIFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFindActionPerformed
        SingleLineEditor DSLE=new SingleLineEditor(RSC, "Please enter a search string.","",true);
        DSLE.setVisible(true);
        search=DSLE.text;
        DSLE.dispose();
        findNext();
    }//GEN-LAST:event_jMIFindActionPerformed

    private void jMIFindNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIFindNextActionPerformed
        findNext();
    }//GEN-LAST:event_jMIFindNextActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMIClose;
    private javax.swing.JMenuItem jMIFind;
    private javax.swing.JMenuItem jMIFindNext;
    private javax.swing.JMenuItem jMISaveCopy;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jStatus;
    private javax.swing.JTextArea jTAContent;
    // End of variables declaration//GEN-END:variables

}
